version: '3.7'
services:
  mkdocs:
    image: polinux/mkdocs:1.1.2
    ports:
    - "8000:8000"
    volumes:
    - .:/mkdocs
    environment:
      ADD_MODULES: 'mkdocs-material'
      LIVE_RELOAD_SUPPORT: 'true'