site_name: Automotive Academy Cloud Expert Program
site_url: https://docs.at.automotive.msg.team/cxp
site_description: Cloud Expert Program documentation
copyright: msg systems ag Automotive Technology
repo_url: https://github.com/msgoat/cxp-dox-home
repo_name: cxp-dox-home
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
theme: material
nav:
  - Home: index.md
  - Virtualization:
      - Virtual Machines: virtualization/virtual_machines.md
      - Installing Hyper-V: virtualization/installing_hyperv.md
  - Linux:
      - Introduction: linux/index.md
      - Creating CentOS8 VM on Hyper-V: linux/centos8_create_vm_hyperv.md
      - Installing CentOS8: linux/centos8_install.md
      - Setting up CentOS8 : linux/centos8_setup.md
  - AWS:
      - Introduction: aws/index.md
      - AWS Accounts: aws/aws_accounts.md
      - AWS Users:
          - User Account Basics: aws/iam/aws_users.md
          - Setting up a Console User Account: aws/iam/aws_console_user_setup.md
          - Setting up a Programmatic User Account: aws/iam/aws_programmatic_user_setup.md
