site_name: Automotive Academy Cloud Expert Program
site_url: https://d2lxv3e7d7f0dt.cloudfront.net/
site_description: Documentation Site of the Automotive Academy Cloud Expert Program
copyright: msg systems ag Automotive Technology
repo_url: https://github.com/msgoat/cxp-dox-home
repo_name: cxp-dox-home
use_directory_urls: false
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
theme: material
nav:
  - Home: index.md
  - Virtualization:
      - Virtual Machines: virtualization/virtual_machines.md
      - Installing Hyper-V: virtualization/hyperv_install.md
      - Installing VirtualBox: virtualization/vbox_install.md
  - Linux:
      - Introduction: linux/index.md
      - Creating CentOS8 VM on Hyper-V: linux/centos8_create_vm_hyperv.md
      - Installing CentOS8: linux/centos8_install.md
      - Setting up CentOS8 : linux/centos8_setup.md
      - Linux Storage Basics : linux/linux_storage_basics.md
      - Adding a new Block Device to CentOS8 : linux/centos8_add_volume.md
      - Growing an existing Block Device on CentOS8 : linux/centos8_grow_volume.md
  - AWS:
      - Introduction: aws/index.md
      - AWS Accounts: aws/aws_accounts.md
      - AWS Users:
          - User Account Basics: aws/iam/aws_users.md
          - Setting up a Console User Account: aws/iam/aws_console_user_setup.md
          - Setting up a Programmatic User Account: aws/iam/aws_programmatic_user_setup.md
      - AWS Virtual Machines (EC2):
          - Creating an EC2 instance: aws/ec2/ec2_create_instance.md
      - AWS Block Storage (EBS):
          - Creating an EBS volume: aws/ebs/ebs_create_volume.md
          - Resizing an EBS volume: aws/ebs/ebs_resize_volume.md
  - SSH:
      - SSH Primer: ssh/ssh_primer.md
      - Connecting to Linux VMs: ssh/ssh_connect_to_vms.md
      - PuTTY Primer: ssh/putty_primer.md
      - Managing Connections with PuTTY: ssh/putty_managing_connections.md
      - Managing SSH Keys with PuTTY: ssh/putty_managing_ssh_keys.md
      - Creating SSH Keys with ssh-keygen: ssh/ssh_create_ssh_keys.md